name: Yaml Lint
on: [push]
jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@master
      with:
        file_or_dir: .
